//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "oauth")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
    pub created_by: i32,
    pub redirect: Vec<String>,
    pub access: Vec<String>,
    pub avatar: Option<String>,
    pub name: String,
    pub description: Option<String>,
    pub homepage: Option<String>,
    pub background: Option<String>,
    pub theme: Option<String>,
    pub policy: Option<String>,
    pub tos: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "(Column::CreatedBy, Column::CreatedBy)",
        to = "(super::account::Column::Id, super::account::Column::Id)",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Account,
    #[sea_orm(has_many = "super::account_oauth::Entity")]
    AccountOauth,
    #[sea_orm(has_many = "super::oauth_client::Entity")]
    OauthClient,
    #[sea_orm(has_many = "super::oauth_log::Entity")]
    OauthLog,
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl Related<super::account_oauth::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountOauth.def()
    }
}

impl Related<super::oauth_client::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OauthClient.def()
    }
}

impl Related<super::oauth_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OauthLog.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
