//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "account")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub openid: String,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
    #[sea_orm(unique)]
    pub username: String,
    pub nickname: Option<String>,
    pub avatar: Option<String>,
    #[sea_orm(unique)]
    pub email: String,
    pub background: Option<String>,
    pub color: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::account_authorization::Entity")]
    AccountAuthorization,
    #[sea_orm(has_many = "super::account_log::Entity")]
    AccountLog,
    #[sea_orm(has_many = "super::account_oauth::Entity")]
    AccountOauth,
    #[sea_orm(has_many = "super::oauth::Entity")]
    Oauth,
    #[sea_orm(has_many = "super::oauth_client::Entity")]
    OauthClient,
    #[sea_orm(has_many = "super::oauth_log::Entity")]
    OauthLog,
}

impl Related<super::account_authorization::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountAuthorization.def()
    }
}

impl Related<super::account_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountLog.def()
    }
}

impl Related<super::account_oauth::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountOauth.def()
    }
}

impl Related<super::oauth::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Oauth.def()
    }
}

impl Related<super::oauth_client::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OauthClient.def()
    }
}

impl Related<super::oauth_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OauthLog.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
