//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod account;
pub mod account_authorization;
pub mod account_log;
pub mod account_oauth;
pub mod oauth;
pub mod oauth_client;
pub mod oauth_log;
