//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::account::Entity as Account;
pub use super::account_authorization::Entity as AccountAuthorization;
pub use super::account_log::Entity as AccountLog;
pub use super::account_oauth::Entity as AccountOAuth;
pub use super::oauth::Entity as OAuth;
pub use super::oauth_client::Entity as OAuthClient;
pub use super::oauth_log::Entity as OAuthLog;
