[package]
edition      = "2024"
name         = "migration"
publish      = false
rust-version = "1.85.0"
version      = "0.1.0"

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
models = { path = "../models" }

tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread"] }

[dependencies.sea-orm-migration]
features = [
  "sqlx-postgres",
  "runtime-tokio-rustls",
  "with-chrono",
  "with-time",
  "with-json",
  "with-uuid",
]
version = "2.0.2"
